# Generated by Django 4.1.5 on 2024-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sales',
            field=models.IntegerField(),
        ),
    ]
